name: Docker Image CI

on:
  workflow_dispatch:
  
jobs:
  build-n-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets._DOCKERUSER }}
        password: ${{ secrets._DOCKERPASS }}

    # - name: Docker Build  
    #   run: docker build . --file Dockerfile --tag hub.docker.com/bijoy26/cis-devsecops:test

    # - shell: bash
    #   run: |
    #       touch dockerfile_report_cis_devsecops[ACTIONS].txt dockerfile_report_ubuntu_bionic[ACTIONS].txt
    #       unbuffer trivy -q config Dockerfile | tee dockerfile_report_cis_devsecops[ACTIONS].txt >/dev/null 2>&1

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: bijoy26/cis-devsecops:test
