name: Trivy Scan
on:
  workflow_dispatch:
jobs:
  trivy-IaC-scan:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.43.1/trivy_0.43.1_Linux-64bit.deb && sudo dpkg -i trivy_0.43.1_Linux-64bit.deb && sudo apt-get install expect-dev
    
      - name: Checkout code
        uses: actions/checkout@v3 
   
      - shell: bash
        run: |
          touch dockerfile_report_cis_devsecops[ACTIONS].txt dockerfile_report_ubuntu_bionic[ACTIONS].txt
          unbuffer trivy -q config Dockerfile | tee dockerfile_report_cis_devsecops[ACTIONS].txt >/dev/null 2>&1
          unbuffer trivy -q config Dockerfile.vuln | tee dockerfile_report_ubuntu_bionic[ACTIONS].txt >/dev/null 2>&1
   
      - name: Push reports to Deployment Server 
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets._SSHHOST }}
          username: ${{ secrets._SSHUSERNAME }}
          port: ${{ secrets._SSHPORT }}
          key: ${{ secrets._SSHKEY }}
          overwrite: true
          source: "*.txt"
          target: /home/cseju/reports
