name: Trivy & Docker Scout Scan
on:
  workflow_dispatch:
jobs:
  trivy-IaC-scan:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.43.1/trivy_0.43.1_Linux-64bit.deb && sudo dpkg -i trivy_0.43.1_Linux-64bit.deb && sudo apt-get install expect-dev
    
      - name: Checkout code
        uses: actions/checkout@v3 
   
      - shell: bash
        run: |
          touch dockerfile_report_cis_devsecops[ACTIONS].txt dockerfile_report_ubuntu_bionic[ACTIONS].txt
          unbuffer trivy -q config Dockerfile | tee dockerfile_report_cis_devsecops[ACTIONS].txt >/dev/null 2>&1
          unbuffer trivy -q config Dockerfile.vuln | tee dockerfile_report_ubuntu_bionic[ACTIONS].txt >/dev/null 2>&1
          
   
      - name: Push reports to Deployment Server 
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets._SSHHOST }}
          username: ${{ secrets._SSHUSERNAME }}
          port: ${{ secrets._SSHPORT }}
          key: ${{ secrets._SSHKEY }}
          overwrite: true
          source: "*.txt"
          target: /home/cseju/reports

  docker-scout-image-scan:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh && sh install-scout.sh && sudo apt-get install expect-dev
 
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets._DOCKERUSER }}
          password: ${{ secrets._DOCKERPASS }}

      - shell: bash
        run: |
          touch base_image_report_cis_devsecops[ACTIONS].txt 
          unbuffer docker scout recommendations bijoy26/cis-devsecops:bumped | tee base_image_report_cis_devsecops[ACTIONS].txt >/dev/null 2>&1
          unbuffer docker scout quickview bijoy26/cis-devsecops:bumped | tee image_quickview_report_cis_devsecops[ACTIONS].txt >/dev/null 2>&1
          unbuffer docker scout cves --ignore-base --only-severity critical,high bijoy26/cis-devsecops:bumped | tee image_vuln_report_cis_devsecops[ACTIONS].txt >/dev/null 2>&1
      
      - name: Push reports to Deployment Server 
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets._SSHHOST }}
          username: ${{ secrets._SSHUSERNAME }}
          port: ${{ secrets._SSHPORT }}
          key: ${{ secrets._SSHKEY }}
          overwrite: true
          source: "*.txt"
          target: /home/cseju/reports

  docker-continuous-deployment-w/-dynamic-analysis:
    needs: [docker-scout-image-scan, docker-scout-image-scan]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy container & perform dynamic analysis
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets._SSHHOST }}
          username: ${{ secrets._SSHUSERNAME }}
          key: ${{ secrets._SSHKEY }}
          port: ${{ secrets._SSHPORT }}
          script: |
            ls -al
            docker run -d -it -p 2222:2222  bijoy26/cis-devsecops:bumped
      # - shell: bash
      #   run: |
      #     curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh && sh install-scout.sh && sudo apt-get install expect-dev